name: BuildOnTag
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo

      - uses: docker/setup-buildx-action@v3
        name: Setup Docker
     
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ github.token }}

      - name: 'Build and push Image'
        run: |
          docker build . --tag ghcr.io/baopdt/bundid-simulator:${{ github.ref_name }}
          docker push ghcr.io/baopdt/bundid-simulator:${{ github.ref_name }}

